<a href="https://colab.research.google.com/github/Grace-1420/Employees.py/blob/main/Employees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import pandas as pd

In [49]:
from google.colab import files
uploaded =files.upload()

Saving employees2.csv.csv to employees2.csv (2).csv

In [50]:
df = pd.read_csv('employees2.csv.csv')

In [51]:
df.isnull().any()

First Name            True
Gender                True
Start Date           False
Last Login Time      False
Salary               False
Bonus %              False
Senior Management     True
Team                  True
dtype: bool

In [52]:
df[df['First Name'].isnull()  == 1]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
25,NaN,Male,10-08-12,1:12 AM,37076,18.576,NaN,Client Services
32,NaN,Male,8/21/1998,2:27 PM,122340,6.417,NaN,NaN
39,NaN,Male,1/29/2016,2:33 AM,122173,7.797,NaN,Client Services
...,...,...,...,...,...,...,...,...
902,NaN,Male,5/23/2001,7:52 PM,103877,6.322,NaN,Distribution
925,NaN,Female,8/23/2000,4:19 PM,95866,19.388,NaN,Sales
946,NaN,Female,9/15/1985,1:50 AM,133472,16.941,NaN,Distribution
947,NaN,Male,7/30/2012,3:07 PM,107351,5.329,NaN,Marketing
951,NaN,Female,9/14/2010,5:19 AM,143638,9.662,NaN,NaN

In [53]:
df['First Name']=df['First Name'].fillna('Unknown')

In [54]:
df['First Name']

0      Douglas
1       Thomas
2        Maria
3        Jerry
4        Larry
        ...
995      Henry
996    Phillip
997    Russell
998      Larry
999     Albert
Name: First Name, Length: 1000, dtype: object

In [55]:
df['Senior Management']

0       True
1       True
2      False
3       True
4       True
       ...
995    False
996    False
997    False
998    False
999     True
Name: Senior Management, Length: 1000, dtype: object

In [56]:
df=df.fillna({'Gender' : 'No Gender', 'Senior Management' : 'None' , 'Team' : 'No Team'})

In [57]:
df['Gender']= df['Gender'].replace('No Gender' , 'NA' )

In [58]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-93,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,No Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-05,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NA,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [59]:
df['Gender']

0        Male
1        Male
2      Female
3        Male
4        Male
        ...
995        NA
996      Male
997      Male
998      Male
999      Male
Name: Gender, Length: 1000, dtype: object

In [60]:
df[df['First Name'] == 'Henry']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
57,Henry,Male,6/26/1996,1:44 AM,64715,15.107,True,Human Resources
136,Henry,Male,4/24/1995,4:18 AM,43542,19.687,False,Legal
259,Henry,Male,02-06-95,8:34 AM,89258,15.585,True,Human Resources
732,Henry,Male,05-12-86,2:04 AM,59943,1.432,False,Finance
752,Henry,Male,2/23/2007,3:24 AM,49665,18.338,False,Business Development
995,Henry,NA,11/23/2014,6:09 AM,132483,16.655,False,Distribution